### ISSUE TITLE
i have created my own training data i got this error 

### ISSUE THREAD

**Issue by KnitVikas** [xashru/punctuation-restoration#5]
2021-04-23 21:22:11.699111: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "src/train.py", line 41, in <module>
    token_style=token_style, is_train=True, augment_rate=ar, augment_type=aug_type)
  File "/content/drive/My Drive/punctuation-restoration/src/dataset.py", line 77, in __init__
    self.data = parse_data(files, tokenizer, sequence_len, token_style)
  File "/content/drive/My Drive/punctuation-restoration/src/dataset.py", line 45, in parse_data
    y.append(punctuation_dict[punc])
KeyError: '0'

HELP PLEASE.

**Comment by xashru** [comment]
`punctuation_dict = {'O': 0, 'COMMA': 1, 'PERIOD': 2, 'QUESTION': 3}`

Its O not zero

**Comment by KnitVikas** [comment]
thanks@(https://github.com/xashru) 

This time i am having another issue please  tell me about the evaluation process for the model ? why i am getting nan in fourth column.
Precision: [0.94953096 0.58869227 0.75925926        nan 0.59628866]
Recall: [0.94099783 0.64583333 0.48809524        nan 0.63421053]
F1 score: [0.94524514 0.61594039 0.5942029         nan 0.61466525]
Accuracy:0.9030138474070052
Confusion Matrix[[15183   926    26     0]
 [  748  1364     0     0]
 [   59    27    82     0]
 [    0     0     0     0]]

**Comment by xashru** [comment]
It looks like you did not have any `QUESTION` in training data, so precision/recall for it is undefined.
